---
#3

- name: default ServerName
  lineinfile:
    dest: "{{ apache_server_root }}/apache2.conf"
    backup: no
    regexp: 'ServerName'
    line: "ServerName {{ hostname }}"
  notify: restart apache

- name: Add utf8 charset
  lineinfile:
    dest: "{{ apache_server_root }}/conf-available/charset.conf"
    backup: no
    regexp: 'AddDefaultCharset'
    line: 'AddDefaultCharset UTF-8'
  notify: restart apache

- name: Enable Apache mods.
  file:
    src: "{{ apache_server_root }}/mods-available/{{ item }}"
    dest: "{{ apache_server_root }}/mods-enabled/{{ item }}"
    state: link
  with_items: "{{ apache_mods_enabled }}"
  notify: restart apache

- name: Disable Apache mods.
  file:
    path: "{{ apache_server_root }}/mods-enabled/{{ item }}"
    state: absent
  with_items: "{{ apache_mods_disabled }}"
  notify: restart apache

# install site from git
- include_tasks: install.yml
  when: site.type == "git"
  with_items: "{{ apache_vhosts }}"
  loop_control:
    loop_var: site


# install site from other link ( ie site/mobile_site)
- include_tasks: link.yml
  when: site.type == "link"
  with_items: "{{ apache_vhosts }}"
  loop_control:
    loop_var: site

# directory ie site/mobile_site)
- include_tasks: directory.yml
  when: site.type == "directory"
  with_items: "{{ apache_vhosts }}"
  loop_control:
    loop_var: site


#copy conf to site
- name: Copy site from template
  template:
    src=vhosts.conf.j2
    dest={{ apache_site_available_location }}/{{item.servername}}.conf
    backup=no
    mode=0644
  with_items: "{{ apache_vhosts }}"
  notify:
    - restart apache

#NEED DETECT apache running standalone
- name: Check apache2
  shell: systemctl status apache2.service | grep Active | awk -v N=2 '{print $N}'
  register: output

- name: cerbot type apache
  set_fact:
    certbot_type:  "apache"
  when:  output.stdout == 'active'

- name: cerbot type standalone
  set_fact:
    certbot_type:  "standalone"
  when:  output.stdout != 'active'

- include_tasks: https.yml
  with_items: "{{ apache_vhosts }}"
  loop_control:
    loop_var: site

- name: renew certicat
  shell: "certbot renew --apache"
  notify:
    - restart apache

#copy conf to site
- name: Copy site from template ssl
  template:
    src=vhosts_ssl.conf.j2
    dest={{ apache_site_available_location }}/{{ item.servername }}_ssl.conf
    backup=no
    mode=0644
  with_items: "{{ apache_vhosts }}"
  notify:
    - restart apache

- name: Enable Apache ssl site.
  file:
    src: "{{ apache_server_root }}/sites-available/{{ item.servername }}_ssl.conf"
    dest: "{{ apache_server_root }}/sites-enabled/{{ item.servername }}_ssl.conf"
    state: link
  with_items: "{{ apache_vhosts }}"
  notify: restart apache


