---
#3

- name: default ServerName
  lineinfile:
    dest: "{{ apache_server_root }}/apache2.conf"
    backup: no
    regexp: 'ServerName'
    line: "ServerName {{ hostname }}"
  notify: restart apache

- name: Add utf8 charset
  lineinfile:
    dest: "{{ apache_server_root }}/conf-available/charset.conf"
    backup: no
    regexp: 'AddDefaultCharset'
    line: 'AddDefaultCharset UTF-8'
  notify: restart apache

- name: Enable Apache mods.
  apache2_module:
    state: present
    name: "{{ item }}"
  with_items: "{{ apache_mods_enabled }}"
  notify: restart apache

- name: Disable Apache mods.
  file:
    path: "{{ apache_server_root }}/mods-enabled/{{ item }}"
    state: absent
  with_items: "{{ apache_mods_disabled }}"
  notify: restart apache

#file with regexp pattern not working
- name: remove all site
  shell:
   cmd: "rm {{ apache_server_root }}/sites-enabled/*.conf"
  ignore_errors: yes
  when: apache_reset is defined

#NEED DETECT apache running standalone
- name: Check apache2
  shell: systemctl status apache2.service | grep Active | awk -v N=2 '{print $N}'
  register: output

- name: cerbot type apache
  set_fact:
    certbot_type:  "apache"
    option: ""
  when:  output.stdout == 'active'

- name: cerbot type standalone
  set_fact:
    certbot_type:  "standalone"
    option: "certonly"
  when:  output.stdout != 'active'

- include_tasks: site.yml
  when: site.noReplication is not defined or hostname == site.mainWebServer
  with_items: "{{ apache_vhosts }}"
  loop_control:
    loop_var: site

- name: renew certicat
  shell: "certbot renew --apache"
  ignore_errors: yes
  notify:
    - restart apache







