- name: update main  site dns
  shell: "
    echo \"server 127.0.0.1\" > /tmp/update.txt; \
    echo \"zone {{ site.zone }}\" >> /tmp/update.txt; \
    echo \"update add {{ site.servername }}.{{ site.zone }}                3600 CNAME {{ hostname }}.{{ site.zone }}\" >> /tmp/update.txt; \
    echo \"update add {{ site.servername }}-{{ hostname }}.{{ site.zone }} 3600 CNAME {{ hostname }}.{{ site.zone }}\" >> /tmp/update.txt; \
    echo \"send\" >> /tmp/update.txt; \
    nsupdate -k /etc/bind/rndc.key -v /tmp/update.txt"
  when: site.webroot is not defined and hostname == site.mainWebServer

- name: update site dns
  shell: "
    echo \"server 127.0.0.1\" > /tmp/update.txt; \
    echo \"zone {{ site.zone }}\" >> /tmp/update.txt; \
    echo \"update add {{ site.servername }}-{{ hostname }}.{{ site.zone }} 3600 CNAME {{ hostname }}.{{ site.zone }}\" >> /tmp/update.txt; \
    echo \"send\" >> /tmp/update.txt; \
    nsupdate -k /etc/bind/rndc.key -v /tmp/update.txt"
  when: site.webroot is not defined and hostname != site.mainWebServer

