- debug:
    msg: "******************** install {{ site.servername }}-{{ hostname }}.{{ domain }} ********************"

- name: certificat  main
  shell: "certbot certonly --non-interactive --agree-tos --{{ certbot_type }} --email {{ letsencrypt_email }}  --domain {{ hostname }}.{{ domain }} --expand"
  ignore_errors: yes
  args:
    creates: "/etc/letsencrypt/live/{{ hostname }}.{{ domain }}"
  when: site.main is defined
#  ignore_errors: yes
  register: result
  notify:
    - restart apache
#--domain {{ site.servername }}.{{ domain }}
- name: certificat
  shell: "certbot certonly --non-interactive --agree-tos --{{ certbot_type }} --email {{ letsencrypt_email }} --domain {{ site.servername }}-{{ hostname }}.{{ domain }}
     --expand"
  ignore_errors: yes
  args:
    creates: "/etc/letsencrypt/live/{{ site.servername }}.{{ domain }}"
  when: site.main is not defined
#  ignore_errors: yes
  register: result
  notify:
    - restart apache

- debug:
    msg: "{{result}}"



- name: construct ssl
  set_fact:
    apache_vhosts_ssl: "{{ apache_vhosts_ssl + [site] }}"
  when: result.changed is true and result.failed is false



