#5

- stat:
    path: "{{ site.directory }}"
  register: sym

- debug:
    msg: "{{ sym }}"

- name: Create a symbolic link
  file:
    src: "{{ site.directory }}"
    dest: "{{ apache_dest_dir }}/{{ site.servername }}"
    state: link
#  ignore_errors: yes
  when: sym.stat.islnk is defined and sym.stat.islnk == False

- name: check permissions
  file:
    path: "{{ site.directory }}"
    mode: 0775

